name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install Dependencies
        run: |
          go mod download

      - name: Run Unit and Integration Tests
        env:
          DB_PATH: ":memory:"  # Use in-memory SQLite database
        run: |
          go test ./... -v
